### ISSUE TITLE
develop here on GitHub

### ISSUE THREAD

**Issue by cfoellmann** [yehudah/Post-SMTP#11]
Hi @yehudah 

I would love to help you with the plugin (I sent you a mail already).
If you add the latest code to the repo I could start coding and sending you PRs to show you what I have in mind.

Cheers,
Chris

**Comment by captainhook** [comment]
@yehudah please do update the repo, I think there are a couple of people at least who would love to contribute towards development.

**Comment by yehudah** [comment]
Hi @cfoellmann ,
You can start to contribute :-) and thanks!

@captainhook I doubt it, I can't count the times I did the syncs from the WordPress repo.

**Comment by cfoellmann** [comment]
You should not need to sync anything manually. See #12 
Let's close this issue for now.
