### ISSUE TITLE
"Security" setting reverts to `None`

### ISSUE THREAD

**Issue by cfoellmann** [yehudah/Post-SMTP#14]
I set up a site a few weeks ago (I suspect pre 1.9.x version of Post-SMTP).
Settings: SMTP on Port 25 + STARTTLS.

Today I realize mails can not be delivered because the setting "Security" reverted to `None`. Server refuses connection because of that.
It was not possible to save a change back to STARTTLS.

That's bad. Even the Connectivity Test shows for Port 25 support for STARTTLS.
The addition to 1.9 concerning encryption detection might be buggy.

**Comment by yehudah** [comment]
Correct, just released a fix.
Check and let me know.

**Comment by NielsdeBlaauw** [comment]
Marking this as fixed.
