### ISSUE TITLE
Notification: Slack as webhook

### ISSUE THREAD

**Issue by cfoellmann** [yehudah/Post-SMTP#15]
If you use slack in the free version you have a limit for the "Slack Apps" you can register to your organization.

I would like to add a 4th notification option: `Slack via Webhook`

The webhook app needs to be activated once for the org and can receive simple notifications from multiple external services.

**Comment by yehudah** [comment]
Hi,

The current one is a webhook option, every user can use the Post SMTP slack app located here:
https://slack.postmansmtp.com/

**Comment by NielsdeBlaauw** [comment]
A slack webhook notification [seems to have been added in the past](https://github.com/yehudah/Post-SMTP/commit/e9a077a74215fb3e8e354403d2a9cbe93947001b), closing this issue.
