### ISSUE TITLE
UI + UX improvements

### ISSUE THREAD

**Issue by cfoellmann** [yehudah/Post-SMTP#17]
I would love to send you PRs to improve on the UI and UX.
Before I start give me some feedback on these items!

- [ ] move settings to "Settings > SMTP"

- [ ] Replicate Core Styling for admin pages: tabbed layout (like on `site-info.php`)

**Comment by yehudah** [comment]
What you suggest was the old location, and I moved it.
about the styling, can you send screenshots?
