### ISSUE TITLE
Replace split() with preg_split() for PHP 7

### ISSUE THREAD

**Issue by awijasa** [yehudah/Post-SMTP#3]
Hello,

I ran a PHP Compatibility Checker (https://wordpress.org/plugins/php-compatibility-checker/) to check for PHP 7 compatibility. It is listing a couple errors related to Post SMTP. Both are about the use of split instead of preg_split.

On /Postman/Postman-Connectivity-Test/registered-domain-libs-master/generateEffectiveTLDs.php:

Line 153: Replace $lines = split("\n", $list); with $lines = preg_split("\n", $list);

Line 179: Replace $tldParts = split('\.', $line); with $tldParts = preg_split('\.', $line);

Thanks,

@awijasa

**Comment by sybrew** [comment]
This issue can be closed as it has already been fixed, at least in 1.8.

**Comment by awijasa** [comment]
Closed. Thanks for the reminder, @sybrew!
