### ISSUE TITLE
Dismiss admin notice 'Postman is not configured and is mimicking out-of-the-box WordPress email delivery'

### ISSUE THREAD

**Issue by jb510** [yehudah/Post-SMTP#39]
There should be a way to dismiss or disable the global admin notice that displays when Postman is not configured.

Dashboard:
![2019-03-20 at 9 42 AM](https://user-images.githubusercontent.com/801241/54702665-8aa42680-4af4-11e9-9fe3-1c740e5ca33d.jpg)
Posts:
![2019-03-20 at 9 43 AM](https://user-images.githubusercontent.com/801241/54702731-b0c9c680-4af4-11e9-8241-4ed08bb95fa0.jpg)
etc... etc... etc...

Post SMTP is amazing and we use it on nearly every site we build. However, many of those sites have no need for a transaction email service.  We _still_ use Post SMTP on them because it's logging ability is incredibly helpful in troubleshooting when things go wrong.

There should either be an standard "dismiss" button on this admin notice (preferred), or
There should be a setting on the settings page to permanently hide it, or
It could just hide itself if the setup screen had been completed and saved with the option of 'default'.

**Comment by yehudah** [comment]
What version do you use?

**Comment by jb510** [comment]
@yehudah this has been like this as long as I can remember.  Those screenshots are from Version 1.9.8 which I believe is the latest.

**Comment by jb510** [comment]
Wait!  no...  those screenshots are from 1.7.2 of Postman!!!

**Comment by jb510** [comment]
Updated to Post SMTP... and this is now dismiss-able.  Sorry about that.  This is an old client's site that just had us do some updates, didn't realize it'd been _that_ long since we'd had involvement with it.

**Comment by yehudah** [comment]
No problems, just send a test email to verify that nothing happen to email delivery.

**Comment by shay3des** [comment]
hi... 
i am using 2.0.12 and have the message...
Postman is not configured and is mimicking out-of-the-box WordPress email delivery.
i tried phpmailer and postsmtp and yet, i have this message and emails goes to spam...
