### ISSUE TITLE
Consider using 'phpmailer_init' hook.

### ISSUE THREAD

**Issue by Pierre-Lannoy** [yehudah/Post-SMTP#51]
Hello @yehudah !

I'm working on a mail logger/archiver ([MailArchiver](https://github.com/Pierre-Lannoy/wp-mailarchiver)) which, obviously, use `wp_mail`, `wp_mail_failed` to catch emails and archive them.
The next version of this archiver plugin will try to use `phpmailer_init` to obtain more detailed information about the sent mail. But, in reading your code, I see you've commented the action call in the `PostmanWpMail` class...
I was wondering for what reason you've done this and if there's a chance you can reconsider it...

Thanks in advance for your time - and for this great plugin I use on all my sites ;)

**Comment by yehudah** [comment]
Hi @Pierre-Lannoy 
it's very nice to get familiar with your work, can't wait to try MailArchiver.

From the next version, I'm doing a lot of effort to integrate delivery to phpmailer.
The users need to change the mailer type from "PostSMTP" to "PHPMailer" (inside settings)

Thank you for using :-)

**Comment by yehudah** [comment]
The link to dev version if you want to give it  try:
https://downloads.wordpress.org/plugin/post-smtp.zip

**Comment by Pierre-Lannoy** [comment]
Hey, thank you for this fast answer :)
I will get a try with this (future) new version and see what's possible with it (from an archiver point of view).
Thanks for all, I'll get in touch.

**Comment by Pierre-Lannoy** [comment]
Hello @yehudah !
Thanks to your help - and some coding hours ;) - MailArchiver is now fully compatible with Post SMTP (whatever the mailer type you choose). So I close this issue.
Thanks again...

https://wordpress.org/plugins/mailarchiver/
