### ISSUE TITLE
Fork is approved!?

### ISSUE THREAD

**Issue by scheinercc** [yehudah/Post-SMTP#9]
Heya,

The readme still says "Until this fork will be approved by the plugins team, we have this fork.", but checking out https://wordpress.org/plugins/post-smtp/ I guess it has been approved in the meantime?

Also the readme here states version 1.7.10 on WP.org it is version 1.8.9. Is this repo outdated?

Thank you for your hard work!

**Comment by captainhook** [comment]
The readme also says right at the top:

> NEW HOME!
> 
> Until this fork will be approved by the plugins team, we have this fork. To make thing more comfortable and so you can still get updates what's going on you are welcome to visit us at: https://postmansmtp.com/
> 
> most of the updates will be here: https://postmansmtp.com/blog

**Comment by cfoellmann** [comment]
Closed by #11
